[筆記來源](https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true&scrollTo=duDj86TfWFof)

#### TensorFlow 是 Google 維護，他是一個 Machine Learning Library。
#### 在 TensorFlow 裡，只有三種物件(?)，<font color='red'> tensors, graphs 與 sessions </font>

- graphs: 這裡沒有確切的值，只有類似等式的關係，比如 Vector1 = Vector2 + Vector3
- sessions: 

> <font color='blue'> Tensor </font> :A <font color='red'>generalization of vectors and matrices to potentially higher dimensions</font>. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes  
> 每個 tensor 都有其 <font color='red'>data type 與 shape</font>
- data type: float32, int32, string...
- shape: 代表 data 的 dimension

> <font color = 'blue'>Graph: </font> Building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

In [1]:
import tensorflow as tf

### 創建一個 tensor 物件。
#### 使用 .Variable() method。
#### 括號內第一個參數代表資料的內容(value)，第二個參數是 data type，而此 tensor 的 shape 是 1(1 個 value)[shape=1 的 tensor，其 shape 又可稱 scale]
#### 此 tensor 的 rank(degree) 是 0。

In [2]:
string = tf.Variable('This is a string', tf.string)

#### 此 tensor 的 rank 是 1。因為 list 可以存很多 value
#### 用 <font color='red'> .rank() </font> 來確認 rank:

In [3]:
rank1_string = tf.Variable(['Hello', 'World'], tf.string)


rank2_string = tf.Variable([['Hello', 'Python'], ['Hello', 'C++'], ['Good', 'day']], tf.string) # 這稱為 matric(矩陣)
print(tf.rank(rank2_string))
rank2_string.shape

Tensor("Rank:0", shape=(), dtype=int32)


TensorShape([Dimension(3), Dimension(2)])

#### <font color='red'>.shape</font>

In [4]:
rank1_string.shape 

TensorShape([Dimension(2)])

##### [2,]
- 只有 1 層 list
- 每個 list 有 2 個 values(注意: list 裡的 value 數必須相同)

In [5]:
rank2_string.shape 

TensorShape([Dimension(3), Dimension(2)])

##### [3, 2]
- 第一層有 3 個 lists
- 每個 list 有 2 個 values(注意: list 裡的 value 數必須相同)

#### <font color='red'>.reshape()</font>

In [6]:
tensor1 = tf.ones([1, 2, 3]) # 第一層有 1 個 list，第二層有 2 個 list，每個 list 有 3 個 elements
print(tensor1.shape)

tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1]) # 第一層有 3 個 lists，其它給 tf 自己算(反正 elements 總數要跟 tensor2 一樣就對了)
print(tensor3.shape)

(1, 2, 3)
(3, 2)


In [7]:
'''用 print(tensor1) 應該出現:
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

print(tensor2):
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

print(tensor3):
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
'''

'用 print(tensor1) 應該出現:\ntf.Tensor(\n[[[1. 1. 1.]\n  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)\n\nprint(tensor2):\ntf.Tensor(\n[[[1.]\n  [1.]\n  [1.]]\n\n [[1.]\n  [1.]\n  [1.]]], shape=(2, 3, 1), dtype=float32)\n\nprint(tensor3):\ntf.Tensor(\n[[1. 1.]\n [1. 1.]\n [1. 1.]], shape=(3, 2), dtype=float32)\n'

#### Tensor 的種類:
- Variable
- Constant
- Placeholder
- SparseTensor
#### 其中除了 variable 外，都是 immuttable

### Evaluating tensor (也就是取得 tensor 的 value):
#### 前面說過 tensor 代表的是部分的計算[就是計算而已沒有結果]  因此要用 <font color='red'>session</font>來取得結果。
#### 關鍵字: <font color='red'> .Session() 與 .eval()</font>

In [8]:
tensor1 = tf.ones([1, 2, 3])
with tf.Session() as sess:
    tensor1.eval() 